language: generic
global:
  - CLIVERSION=0.7.2
matrix:
  include:
    - env:
        - BOARD="Seeeduino:samd:zero"
    - env:
        - BOARD="Seeeduino:samd:seeed_wio_terminal"

before_install:
  - sudo apt-get install --reinstall python3-pip
  - python3 -m pip install
  - sudo apt-get install python3-setuptools
  - wget https://github.com/libgit2/libgit2/releases/download/v1.0.0/libgit2-1.0.0.tar.gz
  - tar xzf libgit2-1.0.0.tar.gz
  - cd libgit2-1.0.0/
  - cmake .
  - make
  - sudo make install
  - sudo ldconfig
  - cd ~
  - git clone https://github.com/Seeed-Studio/ardupy-aip
  - pip3 install pip
  - cd ardupy-aip
  - ls
install:
  - pip3 install -U -e .
  - aip

script: 
  - echo "CI Test"
  - aip install  Seeed-Studio/seeed-ardupy-ultrasonic-sensor
  - aip build 
  
notifications:
  webhooks:
    urls:
      - https://www.travisbuddy.com/
    on_success: never
    on_failure: always